# Generated by Django 2.0.6 on 2018-06-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('mac_address', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('last_position', models.CharField(max_length=128)),
                ('last_seen', models.DateTimeField(verbose_name='Last Seen')),
                ('power', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=128)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Device')),
            ],
        ),
    ]
