# Generated by Django 2.0.6 on 2018-06-09 22:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20180609_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 9, 22, 14, 2, 242334, tzinfo=utc)),
        ),
    ]
