# Generated by Django 2.0.6 on 2018-06-09 23:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20180609_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_position', models.CharField(max_length=128)),
                ('new_position', models.CharField(max_length=128)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='device',
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='movement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.Device'),
        ),
    ]
