# Generated by Django 2.0.6 on 2018-06-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20180609_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='num_moves',
            field=models.IntegerField(default=0),
        ),
    ]
