# Generated by Django 2.0.6 on 2018-06-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_device_num_moves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
    ]
